/* Generated by LSS. Do not edit. */

#ifndef LV_THEME_APPLY_TARGETS_H
#define LV_THEME_APPLY_TARGETS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    char reserved;
} lv_theme_apply_targets_config_t;

/**
 * Reset a config to its default values
 * @param config the config to initialize
 */
void lv_theme_apply_targets_config_init(lv_theme_apply_targets_config_t * config);

/**
 * Initialize the theme
 * @param disp pointer to display (NULL for the default display)
 * @param config the theme config, which is copied
 * @return a pointer to reference this theme later
 */
lv_theme_t * lv_theme_apply_targets_init(lv_display_t * disp, const lv_theme_apply_targets_config_t * config);

/**
 * Check if the theme is initialized
 * @return true if initialized, false otherwise
 */
bool lv_theme_apply_targets_is_inited(void);

/**
 * Get the theme
 * @return a pointer to the theme, or NULL when not initialized
 */
lv_theme_t * lv_theme_apply_targets_get(void);

/**
 * Deinitialize the theme
 */
void lv_theme_apply_targets_deinit(void);

#ifdef __cplusplus
}
#endif

#endif /* LV_THEME_APPLY_TARGETS_H */
