/* Generated by LSS. Do not edit. */

#define LV_USE_PRIVATE_API 1 /* For lv_theme_t */

#include "lv_theme_theme.h"

/*********************
 *      DEFINES
 *********************/



/**********************
 *      TYPEDEFS
 **********************/

typedef struct {

} my_theme_styles_t;

typedef enum {
    DISP_SMALL = 3,
    DISP_MEDIUM = 2,
    DISP_LARGE = 1,
} disp_size_t;

typedef struct {
    lv_theme_t base;
    disp_size_t disp_size;
    int32_t disp_dpi;
    lv_theme_theme_config_t config;
    bool inited;
    my_theme_styles_t styles;

} my_theme_t;

/**********************
 *  STATIC PROTOTYPES
 **********************/

static void style_init_reset(lv_style_t * style);
static void theme_apply(lv_theme_t * th, lv_obj_t * obj);
static void resolution_change_event_cb(lv_event_t * e);

/**********************
 *  STATIC VARIABLES
 **********************/

static my_theme_t * theme_def = NULL;

/**********************
 *   STATIC FUNCTIONS
 **********************/

static inline lv_obj_t * lss_ancestor(lv_obj_t * obj, uint32_t depth)
{
    while(obj != NULL && depth > 0) {
        obj = lv_obj_get_parent(obj);
        depth--;
    }
    return obj;
}

static inline bool lss_is_child(lv_obj_t * parent, int32_t index, lv_obj_t * child)
{
    return parent != NULL && lv_obj_get_child(parent, index) == child;
}

static bool config_equals(const lv_theme_theme_config_t * a, const lv_theme_theme_config_t * b)
{
    LV_UNUSED(a);
    LV_UNUSED(b);
    return true;
}

static void style_init(my_theme_t * theme)
{

}

/**********************
 *   GLOBAL FUNCTIONS
 **********************/

void lv_theme_theme_config_init(lv_theme_theme_config_t * config)
{
    lv_memzero(config, sizeof(*config));
}

lv_theme_t * lv_theme_theme_init(lv_display_t * disp, const lv_theme_theme_config_t * config)
{
    if(!lv_theme_theme_is_inited()) {
        theme_def = lv_malloc_zeroed(sizeof(my_theme_t));
        LV_ASSERT_MALLOC(theme_def);
    }

    my_theme_t * theme = theme_def;

    lv_display_t * new_disp = disp == NULL ? lv_display_get_default() : disp;
    int32_t new_dpi = lv_display_get_dpi(new_disp);
    int32_t hor_res = lv_display_get_horizontal_resolution(new_disp);
    int32_t ver_res = lv_display_get_vertical_resolution(new_disp);
    int32_t greater_res = LV_MAX(hor_res, ver_res);
    disp_size_t new_size;

    if(greater_res <= 320) new_size = DISP_SMALL;
    else if(greater_res < 720) new_size = DISP_MEDIUM;
    else new_size = DISP_LARGE;

    if(theme->inited && theme->disp_dpi == new_dpi && theme->disp_size == new_size &&
       config_equals(&theme->config, config)) {
        return (lv_theme_t *) theme;
    }

    theme->disp_size = new_size;
    theme->disp_dpi = new_dpi;
    theme->config = *config;
    theme->base.disp = new_disp;
    theme->base.apply_cb = theme_apply;
    theme->base.font_small = LV_FONT_DEFAULT;
    theme->base.font_normal = LV_FONT_DEFAULT;
    theme->base.font_large = LV_FONT_DEFAULT;

    style_init(theme);

    if(disp == NULL || lv_display_get_theme(disp) == (lv_theme_t *)theme) {
        lv_obj_report_style_change(NULL);
    }

    theme->inited = true;

    /* Re-initialize the styles when the resolution changes, as the display size affects the styles */
    lv_display_remove_event_cb_with_user_data(new_disp, resolution_change_event_cb, theme);
    lv_display_add_event_cb(new_disp, resolution_change_event_cb, LV_EVENT_RESOLUTION_CHANGED, theme);

    return (lv_theme_t *) theme;
}

bool lv_theme_theme_is_inited(void)
{
    return theme_def != NULL && theme_def->inited;
}

lv_theme_t * lv_theme_theme_get(void)
{
    if(!lv_theme_theme_is_inited()) {
        return NULL;
    }
    return (lv_theme_t *) theme_def;
}

void lv_theme_theme_deinit(void)
{
    my_theme_t * theme = theme_def;
    if(theme) {
        if(theme->inited) {
            lv_style_t * theme_styles = (lv_style_t *)(&(theme->styles));
            uint32_t i;
            for(i = 0; i < sizeof(my_theme_styles_t) / sizeof(lv_style_t); i++) {
                lv_style_reset(theme_styles + i);
            }
        }
        lv_free(theme_def);
        theme_def = NULL;
    }
}

/**********************
 *   STATIC FUNCTIONS
 **********************/

static void theme_apply(lv_theme_t * th, lv_obj_t * obj)
{
    LV_UNUSED(th);

    my_theme_t * theme = theme_def;
    lv_obj_t * parent = lv_obj_get_parent(obj);
    LV_UNUSED(theme);
    LV_UNUSED(parent);


}

static void style_init_reset(lv_style_t * style)
{
    if(lv_theme_theme_is_inited()) {
        lv_style_reset(style);
    }
    else {
        lv_style_init(style);
    }
}

static void resolution_change_event_cb(lv_event_t * e)
{
    lv_display_t * disp = lv_event_get_target(e);
    my_theme_t * theme = lv_event_get_user_data(e);
    lv_theme_theme_init(disp, &theme->config);
}
